.DEFAULT_GOAL := help

help:
	@echo "Targets:"
	@echo "  docker-run: Run docker image"

docker-run:
	docker run -d --restart=always -p 3000:3000 southamerica-east1-docker.pkg.dev/tp-bcc361/rock-paper-scissor/tp-bcc361
