name: rock_paper_scissors_frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  pretty_dio_logger: ^1.3.1
  sliver_tools: ^0.2.12
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
